version: "3.7"

services:
  api:
    build: 
      context: ./api
    container_name: api
    environment:
      - CONNECTION_STRING=postgres://postgres:postgres@db/postgres_db
    command: node index.js
    volumes:
     - ./api:/api
    networks:
      - private

  web:
    build: 
      context: ./web
    container_name: web
    environment:
      - API_URL=http://api:3001/data
    command: node index.js
    volumes:
      - ./web:/web
    ports:
      - "80:3000"
    networks:
      - public
      - private

  db:
    image: postgres:11.2-alpine
    ports: ["5432"]
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_db"
    volumes:
      - "/home/ubuntu/docker-compose-belt2/sql_scripts/:/docker-entrypoint-initdb.d"
    networks:
      - public

networks:
  public:
  private: